### ISSUE TITLE
001: Taylor Swift第七张个人专辑《Lover》新单曲《You Need To Calm Down》[FLAC格式]下载

### ISSUE THREAD

**Issue by littleflute** [littleflute/weixin#242]
Taylor Swift第七张个人专辑《Lover》新单曲《You Need To Calm Down》[FLAC格式]下载
https://www.52flac.com/download/10474.html

**Comment by shanuan** [comment]
https://pan.baidu.com/s/1WrZnt71t7PY8qFNWyP0ELQ 提取码：8pw6

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/Pv7MAm15s3-c5N6Cae7MAw
