### ISSUE TITLE
002: 陈百强一首忧郁空灵的歌《一生何求》[FLAC格式]

### ISSUE THREAD

**Issue by littleflute** [littleflute/weixin#243]
https://www.52flac.com/gangtai/9954.html 陈百强一首忧郁空灵的歌《一生何求》[FLAC格式]

**Comment by shanuan** [comment]
链接：https://pan.baidu.com/s/1_AFUWtqTgv9bnVCOg2BKBg 提取码：6t91

**Comment by shanuan** [comment]
https://github.com/shanuan/flac1/releases/tag/002.flac

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/32b3PRnEdWNm7wbZcU6fsw
