### ISSUE TITLE
003: 马良 孙茜茹合唱《往后余生》嗓音独特唱得太醉心[FLAC格式]

### ISSUE THREAD

**Issue by littleflute** [littleflute/weixin#244]
https://www.52flac.com/neidi/9443.html 马良 孙茜茹合唱《往后余生》嗓音独特唱得太醉心[FLAC格式]

**Comment by shanuan** [comment]
https://pan.baidu.com/s/1B4iIVvPXyWYj1QPPYQwdhw 提取码：k4in

**Comment by shanuan** [comment]
https://github.com/shanuan/flac1/releases/download/002/003.flac

**Comment by littleflute** [comment]
https://mp.weixin.qq.com/s/gqQAfjF066-Bp1mdqPcAag
